# Generated by Django 3.2.9 on 2021-12-01 20:49

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Lawyer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Negotiation',
            fields=[
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(help_text='Enter a short, memorable title.', max_length=64)),
                ('cost_type', models.CharField(choices=[('P', 'Price'), ('R', 'Rate')], default='P', help_text='Select the type of cost you will charge.', max_length=1)),
                ('amount', models.DecimalField(decimal_places=2, default=0, help_text='Include the base rate for hiring you.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))])),
                ('initial_amount', models.DecimalField(decimal_places=2, default=0, help_text='How much of the base rate must be paid before you begin work?.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))])),
                ('is_accepted', models.BooleanField(default=False, verbose_name='Do you want to accept the offer?')),
                ('is_changeable', models.BooleanField(default=False, verbose_name='Do you want to change the cost in the future?')),
                ('client_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negotiations.client')),
                ('lawyer_key', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='negotiations.lawyer')),
            ],
            options={
                'ordering': ['title'],
            },
        ),
    ]
