# Generated by Django 3.2.9 on 2021-12-01 21:06

from decimal import Decimal
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negotiations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='negotiation',
            name='budget',
            field=models.DecimalField(decimal_places=2, default=100, help_text='Set the limit for spending on the base cost.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='Include the base cost for hiring you.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
        migrations.AlterField(
            model_name='negotiation',
            name='initial_amount',
            field=models.DecimalField(decimal_places=2, default=0, help_text='How much of the base cost must be paid before you begin work?.', max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0.00')), django.core.validators.MaxValueValidator(Decimal('9999.99'))]),
        ),
    ]
